### ISSUE TITLE
Hexanoughts wrong color

### ISSUE THREAD

**Issue by AydanL** [Taureon/aps-plus-plus#187] opened 2024-02-02 18:03 UTC
for some reason hexanoughts are always purple instead of teal... weird isn't it?

**Comment by Frostbyte178** [comment] 2024-02-02 19:29
aps++ hexagons are magenta so the dreads are too, I can add a toggle later

**Comment by AydanL** [comment] 2024-02-03 10:44
oh lol didn't know you eventually switched hexagons to magenta

**Comment by Zephiii** [comment] 2024-02-04 16:39
closed as works as intended

**Closed by Zephiii** 2024-02-04 16:39 UTC
Labels: Works As Intended

**Comment by Zephiii** [comment] 2024-04-08 15:47
reclosed as "fixed" now that arras.io actually differentiates hexas and legendaries
