### ISSUE TITLE
rare shapes go gigantic in growth

### ISSUE THREAD

**Issue by YanisDiss** [Taureon/aps-plus-plus#163] opened 2023-12-28 12:05 UTC
can u make it so growth doesnt affect shapes
![Screenshot (155)](https://github.com/Taureon/aps-plus-plus/assets/77635886/8a6ade45-5161-4c0a-9c00-72ad449b23ab)

**Comment by idkwhattoget** [comment] 2023-12-28 12:50
this is a thing in normal arras too

**Comment by Zenphia** [comment] 2024-01-12 16:37
Duplicate of https://github.com/Taureon/aps-plus-plus/issues/156

**Comment by Zenphia** [comment] 2024-01-16 17:50
Not actually a duplicate, whoops

**Closed** 2024-04-05 20:10 UTC
Labels: Bug, Not Intended Behavior, Server Side Bug
